#ifndef CONFIGS\REGRESSION\DTR_REG_H_INCLUDED
#define CONFIGS\REGRESSION\DTR_REG_H_INCLUDED
#define NUM_FEATURES 2
#define NUM_NODES 199
extern const int LEFT_CHILDREN[NUM_NODES];
extern const int RIGHT_CHILDREN[NUM_NODES];
extern const int SPLIT_FEATURE[NUM_NODES];
extern const float THRESHOLDS[NUM_NODES];
extern const float VALUES[NUM_NODES];
#endif