#ifndef CONFIGS\REGRESSION\KNN_REG_H_INCLUDED
#define CONFIGS\REGRESSION\KNN_REG_H_INCLUDED
#define NUM_NEIGHBORS 5
#define NUM_FEATURES 2
#define NUM_SAMPLES 100
extern const float DATA[NUM_SAMPLES][NUM_FEATURES];
extern const float DATA_VALUES[NUM_SAMPLES];
#endif