#ifndef CONFIGS\CLASSIFICATION\KNN_CLASSIFIER_H_INCLUDED
#define CONFIGS\CLASSIFICATION\KNN_CLASSIFIER_H_INCLUDED
#define NUM_CLASSES 2
#define NUM_NEIGHBORS 5
#define NUM_FEATURES 2
#define NUM_SAMPLES 160
extern char* LABELS[NUM_CLASSES];
extern const float DATA[NUM_SAMPLES][NUM_FEATURES];
extern const int DATA_LABELS[NUM_SAMPLES];
#endif